import { expect } from "chai";
import { ethers } from "hardhat";
// @ts-ignore
import { poseidonContract } from "circomlibjs";
import { createDeposit, ZKTree, generateProofAndCalldata } from "../src/zk-utils";

describe("ZK Private Vault & 1-to-4 Splitter", function () {
  this.timeout(120000); // Allow sufficient time for snarkjs proof generation

  let deployer: any;
  let alice: any; // Depositor
  let bob: any; // Recipient 1
  let charlie: any; // Recipient 2
  let dave: any; // Recipient 3
  let eve: any; // Recipient 4
  let relayer: any; // Kurir

  let poseidonInstance: any;
  let verifierContract: any;
  let vaultContract: any;

  beforeEach(async function () {
    [deployer, alice, bob, charlie, dave, eve, relayer] = await ethers.getSigners();

    // 1. Deploy Poseidon (2 inputs) bytecode generated by circomlibjs
    const PoseidonABI = poseidonContract.generateABI(2);
    const PoseidonBytecode = poseidonContract.createCode(2);
    const PoseidonFactory = new ethers.ContractFactory(PoseidonABI, PoseidonBytecode, deployer);
    poseidonInstance = await PoseidonFactory.deploy();
    await poseidonInstance.waitForDeployment();
    const poseidonAddress = await poseidonInstance.getAddress();

    // 2. Deploy Groth16Verifier
    const VerifierFactory = await ethers.getContractFactory("Groth16Verifier");
    verifierContract = await VerifierFactory.deploy();
    await verifierContract.waitForDeployment();
    const verifierAddress = await verifierContract.getAddress();

    // 3. Deploy ZKVault
    const VaultFactory = await ethers.getContractFactory("ZKVault");
    vaultContract = await VaultFactory.deploy(verifierAddress, poseidonAddress);
    await vaultContract.waitForDeployment();
  });

  it("Should deposit 1.0 ETH and update on-chain Merkle root correctly", async function () {
    const { poseidon, deposit } = await createDeposit();
    const zkTree = new ZKTree(8, poseidon);

    // Initial root comparison
    const initialContractRoot = await vaultContract.getLastRoot();
    expect(initialContractRoot).to.equal(zkTree.getRoot());

    // Alice deposits 1.0 ETH
    const tx = await vaultContract.connect(alice).deposit(deposit.commitment, {
      value: ethers.parseEther("1.0"),
    });
    await tx.wait();

    // Update off-chain tree
    zkTree.insert(deposit.commitment);

    // On-chain root should match off-chain root
    const updatedContractRoot = await vaultContract.getLastRoot();
    expect(updatedContractRoot).to.equal(zkTree.getRoot());
  });

  it("Should successfully withdraw and split 1.0 ETH across 4 recipients via Relayer", async function () {
    const { poseidon, deposit } = await createDeposit();
    const zkTree = new ZKTree(8, poseidon);

    // Alice deposits 1.0 ETH
    await vaultContract.connect(alice).deposit(deposit.commitment, {
      value: ethers.parseEther("1.0"),
    });
    const leafIndex = zkTree.insert(deposit.commitment);

    // Record initial recipient balances
    const recipients = [bob.address, charlie.address, dave.address, eve.address];
    const initialBalances = await Promise.all(
      recipients.map((addr) => ethers.provider.getBalance(addr))
    );

    // Alice generates Merkle proof and ZK proof off-chain
    const merkleProof = zkTree.generateProof(leafIndex);
    const { pA, pB, pC } = await generateProofAndCalldata(deposit, merkleProof, recipients);

    // Relayer executes withdrawSplit on behalf of Alice
    const tx = await vaultContract.connect(relayer).withdrawSplit(
      pA,
      pB,
      pC,
      merkleProof.root,
      deposit.nullifierHash,
      [bob.address, charlie.address, dave.address, eve.address]
    );
    await tx.wait();

    // Verify each recipient received exactly 0.25 ETH
    const finalBalances = await Promise.all(
      recipients.map((addr) => ethers.provider.getBalance(addr))
    );
    for (let i = 0; i < 4; i++) {
      expect(finalBalances[i] - initialBalances[i]).to.equal(ethers.parseEther("0.25"));
    }

    // Verify nullifier is marked as spent
    expect(await vaultContract.nullifierSpent(deposit.nullifierHash)).to.be.true;
  });

  it("Should prevent double-spending with the same ZK coupon / nullifier", async function () {
    const { poseidon, deposit } = await createDeposit();
    const zkTree = new ZKTree(8, poseidon);

    await vaultContract.connect(alice).deposit(deposit.commitment, {
      value: ethers.parseEther("1.0"),
    });
    const leafIndex = zkTree.insert(deposit.commitment);

    const recipients = [bob.address, charlie.address, dave.address, eve.address];
    const merkleProof = zkTree.generateProof(leafIndex);
    const { pA, pB, pC } = await generateProofAndCalldata(deposit, merkleProof, recipients);

    // 1st withdrawal should succeed
    await vaultContract.connect(relayer).withdrawSplit(
      pA,
      pB,
      pC,
      merkleProof.root,
      deposit.nullifierHash,
      [bob.address, charlie.address, dave.address, eve.address]
    );

    // 2nd withdrawal with the same nullifier should REVERT
    await expect(
      vaultContract.connect(relayer).withdrawSplit(
        pA,
        pB,
        pC,
        merkleProof.root,
        deposit.nullifierHash,
        [bob.address, charlie.address, dave.address, eve.address]
      )
    ).to.be.revertedWith("Nullifier already spent (double-spending prevented)");
  });

  it("Should prevent front-running: Relayer cannot substitute a recipient address", async function () {
    const { poseidon, deposit } = await createDeposit();
    const zkTree = new ZKTree(8, poseidon);

    await vaultContract.connect(alice).deposit(deposit.commitment, {
      value: ethers.parseEther("1.0"),
    });
    const leafIndex = zkTree.insert(deposit.commitment);

    // Alice created proof for Bob, Charlie, Dave, Eve
    const honestRecipients = [bob.address, charlie.address, dave.address, eve.address];
    const merkleProof = zkTree.generateProof(leafIndex);
    const { pA, pB, pC } = await generateProofAndCalldata(deposit, merkleProof, honestRecipients);

    // Malicious relayer attempts to replace Eve with themselves!
    const maliciousRecipients = [bob.address, charlie.address, dave.address, relayer.address];

    await expect(
      vaultContract.connect(relayer).withdrawSplit(
        pA,
        pB,
        pC,
        merkleProof.root,
        deposit.nullifierHash,
        maliciousRecipients as [string, string, string, string]
      )
    ).to.be.revertedWith("Invalid Zero-Knowledge proof");
  });
});
